apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'dagger.hilt.android.plugin'

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withInputStream { stream ->
        localProperties.load(stream)
    }
}

def coindeskApiKey = localProperties.getProperty('COINDESK_API_KEY')
        ?: project.findProperty('COINDESK_API_KEY')
        ?: System.getenv('COINDESK_API_KEY')
        ?: localProperties.getProperty('CRYPTOCOMPARE_API_KEY')
        ?: project.findProperty('CRYPTOCOMPARE_API_KEY')
        ?: System.getenv('CRYPTOCOMPARE_API_KEY')
        ?: ''
def escapedCoindeskApiKey = coindeskApiKey.toString()
        .replace('\\', '\\\\')
        .replace('"', '\\"')

android {
    namespace "app.khom.pavlo.crypto"

    compileSdk 35

    defaultConfig {
        applicationId "app.khom.pavlo.crypto"
        minSdkVersion 23
        targetSdkVersion 35
        versionCode 19
        versionName "1.1.9"
        multiDexEnabled true
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        buildConfigField "String", "COINDESK_API_KEY", "\"${escapedCoindeskApiKey}\""

        javaCompileOptions {
            annotationProcessorOptions {
                arguments = [
                        "room.schemaLocation": "$projectDir/schemas".toString()
                ]
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }

    sourceSets {
        test.java.srcDirs += 'src/test/kotlin'
        androidTest.java.srcDirs += 'src/androidTest/kotlin'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        viewBinding true
        dataBinding true
        buildConfig true
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    androidTestImplementation 'androidx.test:runner:1.7.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    // multidex
    implementation 'androidx.multidex:multidex:2.0.1'

    // Kotlin
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    testImplementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    testImplementation "org.jetbrains.kotlin:kotlin-test-junit:$kotlin_version"

    // Unit
    testImplementation 'com.nhaarman:mockito-kotlin:1.6.0'
    testImplementation 'org.amshove.kluent:kluent:1.73'

    // Hilt
    implementation 'com.google.dagger:hilt-android:2.58'
    kapt 'com.google.dagger:hilt-compiler:2.58'

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0'
    implementation 'androidx.viewpager:viewpager:1.1.0'
    implementation 'androidx.work:work-runtime-ktx:2.9.0'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'com.google.android.gms:play-services-ads:25.2.0'

    // Retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:3.0.0'

    // RxJava
    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxkotlin:2.4.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-appcompat-v7-kotlin:2.2.0'
    implementation 'com.jakewharton.rxbinding2:rxbinding-design-kotlin:2.2.0'

    // Room
    implementation "androidx.room:room-runtime:2.8.4"
    implementation "androidx.room:room-rxjava2:2.8.4"
    kapt "androidx.room:room-compiler:2.8.4"

    implementation 'org.glassfish:javax.annotation:10.0-b28'
    implementation 'com.squareup.picasso:picasso:2.71828'
    implementation 'com.github.ybq:Android-SpinKit:1.1.0'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.2'

}
